---
dotfiles_repo: git@github.com:njetten/dotfiles.git 
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/projects/dotfiles
dotfiles_files:
  - .config
  - .zshrc
  - bin

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_installed_packages:
  - nvim
  - git
  - gawk
  - gnu-sed
  - rbenv
  - gpg
  - ripgrep
  - direnv
  - nmap
  - mariadb
  - postgresql
  - nodenv
  - name: go
    install_options: devel

homebrew_cask_apps:
  - iterm2
  - google-chrome
  - firefox
  - mattermost
  - vagrant
  - virtualbox

mas_installed_apps:
  - { id: 946399090, name: "Telegram Desktop" } 
